name: This tool check syntax of PHP files faster than serial check with fancier output.

on: [ push ]

jobs:
    style:
        runs-on: ubuntu-latest

    steps:
        -   name: Checkout code
            uses: actions/checkout@v1

        -   name: lint php
